### PR TITLE
Add related project - wluma

### PR DESCRIPTION
**Pull request by max-baz**
Hi @anishathalye,

I stumbled upon your blog post about Lumen and got inspired to create an app with similar goal for Linux (specifically, wlroots-based Wayland compositors). Let me just say first, Lumen is a really awesome idea!

In addition to screen contents, I decided to also take into account the value of ambient light sensor (so that full-screen browser window might result in 100% brightness during the day and only 5% during the night).

I also decided to implement all heavy computation on GPU, this way the performance impact is minimal and I'm able to run algorithm several times a second with almost zero resource usage, so that the app can detect very quickly when I change from dark terminal to bright browser.

Maybe these ideas will give you some additional inspiration 🙂 

On a related note, may I re-use your demo GIF on my project? I'm not going to edit out the name, I think it is simply a brilliant way to showcase the purpose of the app.

### CODE REVIEW

**Comment by anishathalye** [comment]
Very cool! It's interesting that the GPU helps out here. Out of curiosity, what's the GPU utilization from this? Also, how do you get the screen pixels in the first place (does it involve a CPU -> GPU transfer, or do you have some way of capturing the screen directly from the GPU)?

Feel free to use the demo GIF. Also, if you want your project in [this list](https://github.com/anishathalye/lumen#related-projects), please open a PR.

**Comment by max-baz** [comment]
> Out of curiosity, what's the GPU utilization from this?

From what I see in `intel_gpu_top`, it grows not more than by 1-2% from the baseline - simply scrolling in Chrome shows a lot more GPU usage...

> Also, how do you get the screen pixels in the first place (does it involve a CPU -> GPU transfer, or do you have some way of capturing the screen directly from the GPU)?

This is the main trick, zero copy 🙂 On Linux the capabilities depend on the window manager and compositor of your choice, in my case I have Wayland and wlroots-based compositor, and it has a dedicated protocol called [export-dmabuf](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-export-dmabuf-unstable-v1.xml) which exposes direct access to a frame of the screen contents on GPU in a DMA-BUF format - then I use Vulkan API to convert this buffer on GPU to an image (so the pixels never leave GPU), and then I use blit functionality to generate mipmaps (scale the image down by half, again and again until you reach 1x1 px image). Then and only then I export the RGB value of the final 1x1 mipmap to CPU, and this color approximates the average screen color, which I then convert to a "lightness" value.

> Feel free to use the demo GIF.

Thank you!

> Also, if you want your project in this list, please open a PR.

This is the PR 😄

**Comment by anishathalye** [comment]
Thanks for the explanation! That is very neat that the whole thing is zero copy. The mipmap trick is neat too! (I wonder if a similar implementation is possible on macOS…)

> This is the PR 😄

Oops I don't know how I missed that, for some reason I thought it was an issue. Merged.

**Comment by max-baz** [comment]
> I wonder if a similar implementation is possible on macOS…

If you manage to find this out and start implementing for macOS, feel free to ping me for a help or just a chat 👍  This was the very first time I had to do GPU programming, but I will hopefully be able to provide you with some guidance or hints. 

Also know that Vulkan API is cross-platform, so once the image is available on GPU, the rest of the code (for mipmap generation) can be pretty-much re-used.

**Comment by anishathalye** [comment]
Will do, thanks! Probably not working on this right away, but when I next have some free time, I will look into it.

**Pull request merged**
